In [2]:
import pandas as pd

In [3]:
# Csv - comma separated value file

data = pd.read_csv('titanic.csv')
data.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [ ]:
data.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
data.shape

(891, 12)

# Unique and Nunique

In [ ]:
data['Survived'].unique() # What are the unique values

array([0, 1])

In [ ]:
data['Survived'].nunique() # How many unique values

2

In [ ]:
(data['Survived'].value_counts() / data.shape[0])*100

Survived
0    61.616162
1    38.383838
Name: count, dtype: float64

In [ ]:
data['Survived'].value_counts(normalize  = True)*100

Survived
0    61.616162
1    38.383838
Name: proportion, dtype: float64

# isna()

In [ ]:
data.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [ ]:
data.isna().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [ ]:
data['Embarked'].value_counts(normalize  =True)

Embarked
S    0.724409
C    0.188976
Q    0.086614
Name: proportion, dtype: float64

In [ ]:
data['Embarked'].value_counts() / 889

Embarked
S    0.724409
C    0.188976
Q    0.086614
Name: count, dtype: float64

In [ ]:
data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
data['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

# pandas filtering

In [9]:
# Senior Citizens

filter = data["Age"] >= 60

filter.sum()

26

In [11]:
filter

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [14]:
data[filter].shape

(26, 12)

In [ ]:
a = 5 # assignment operator a <- 5

a == 5 # Equality operator

In [15]:
# Senior citizens who survived

filter1 =  data["Age"] >= 60
filter2 = data['Survived'] == 1

data[filter1 & filter2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
366,367,1,1,"Warren, Mrs. Frank Manley (Anna Sophia Atkinson)",female,60.0,1,0,110813,75.2500,D37,C
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
587,588,1,1,"Frolicher-Stehli, Mr. Maxmillian",male,60.0,1,1,13567,79.2000,B41,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN

In [17]:
data[(data["Age"] >= 60) & (data['Survived'] == 0)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
684,685,0,2,"Brown, Mr. Thomas William Solomon",male,60.0,1,1,29750,39.0000,NaN,S
694,695,0,1,"Weir, Col. John",male,60.0,0,0,113800,26.5500,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [19]:
# Average age of senior citizens who have not survived
data2 = data[(data["Age"] >= 60) & (data['Survived'] == 0)]

# data[(data["Age"] >= 60) & (data['Survived'] == 0)]["Age"] # This is also possible


data2['Age'].mean() # min(), max(), sum()

# Ass-1
# for loop to come up with the mean() of pandas series

65.39473684210526

In [22]:
data2['Age'].min(), data2['Age'].max()

(60.0, 74.0)

# Saving files in pandas

In [24]:
data2.to_csv("titanic_filtered.csv")

In [25]:
df = pd.read_csv('titanic_filtered.csv')

In [27]:
df.shape

(19, 13)

## Group By in Pandas

In [31]:
data2.groupby('Embarked')["Age"].mean()

Embarked
C    69.000000
Q    67.750000
S    64.285714
Name: Age, dtype: float64

In [37]:
df = data2.groupby("Embarked").agg(mean_of_age=('Age', 'mean'))

In [38]:
data2.groupby("Embarked").agg(mean_of_age=('Age', 'mean'))

          mean_of_age
Embarked
C           69.000000
Q           67.750000
S           64.285714

In [39]:
df.columns

Index(['mean_of_age'], dtype='object')

In [40]:
df.index

Index(['C', 'Q', 'S'], dtype='object', name='Embarked')

In [45]:
df2 = data2.groupby("Embarked").agg(mean_of_age=('Age', 'mean')).reset_index()

In [46]:
df2

  Embarked  mean_of_age
0        C    69.000000
1        Q    67.750000
2        S    64.285714

In [48]:
data1 = data[data['Survived'] == 1]

data1.groupby('Sex').agg(count_of_survived = ('Survived', 'count')).reset_index()

      Sex  count_of_survived
0  female                233
1    male                109

In [49]:
data[data['Survived'] == 1].groupby('Sex').size()

Sex
female    233
male      109
dtype: int64

## Column handling

In [51]:
data[['Age','Embarked']]

      Age Embarked
0    22.0        S
1    38.0        C
2    26.0        S
3    35.0        S
4    35.0        S
..    ...      ...
886  27.0        S
887  19.0        S
888   NaN        S
889  26.0        C
890  32.0        Q

[891 rows x 2 columns]

# Label Encoding

In [58]:
# encoding = {"S": 0,
#             "C": 1,
#             "Q": 2}


def encode(row):
  if row == "S":
    return 0
  elif row == "C":
    return 1
  elif row == "Q":
    return 2
  else:
    return 3



data["Emabarked_encoded_fun"] = data["Embarked"].apply(encode)


# Ass-2
# Use Lambda function to achieve the Lable encoding

In [60]:
encoding = {"S": 0,
            "C": 1,
            "Q": 2}

data["Embarked_encoded_dict"] = data["Embarked"].map(encoding)
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Emabarked_encoded_fun,Embarked_encoded_dict
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,0.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,1.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,0.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0,0.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0,0.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0,0.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0,0.0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1,1.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,2,2.0

In [61]:
data["Age"].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

# One hot encoding

In [63]:
df_ohencode = pd.get_dummies(data, columns= ["Sex"], drop_first = True)

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Emabarked_encoded_fun,Embarked_encoded_dict,Sex_male
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S,0,0.0,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C,1,1.0,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,0.0,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S,0,0.0,False
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S,0,0.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,NaN,S,0,0.0,True
887,888,1,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,B42,S,0,0.0,False
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,1,2,W./C. 6607,23.4500,NaN,S,0,0.0,False
889,890,1,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,C148,C,1,1.0,True
890,891,0,3,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,NaN,Q,2,2.0,True

In [ ]:
# Ass- 3
# 0 -12 - "Child"
# 13 - 19 - "Teen"
# 20 - 60 - "Adults"
# > 60 - "Seniors"

# One hot encoding categories